services:
  - type: web
    name: crypto-price-predictor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:app
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
    autoDeploy: true